### build stage
FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build

### deploy stage
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Opcional: copiar un nginx.conf personalizado si quieres (para SPA routing)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
