FROM python:3.10-slim

WORKDIR /app
COPY backend/ .
RUN pip install --no-cache-dir -r requirements.txt
ENV MODEL_PATH="models/modelo_ropa_50clases.h5"

EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
